# This is a simple example.
# It looks for pods in the default namespace with a label 'prometheus' set to 'application-monitoring'
# They will be scraped for prometheus metrics
#
# apiVersion: monitoring.coreos.com/v1
# kind: PodMonitor
# metadata:
#   name: prometheus
# spec:
#   selector:
#     matchLabels:
#       prometheus: application-monitoring
#   namespaceSelector:
#     matchNames:
#       - "default"

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: prometheus-podmonitor
  namespace: default
spec:
  selector:
    matchLabels:
      app: prometheus-client2  # Matches the label of the Pods to monitor
  namespaceSelector:
    matchNames:
      - default  # Namespace where the Pods are running
  podMetricsEndpoints:
    - port: http  # The name of the port in the Pod exposing metrics
      path: /metrics  # Path where metrics are exposed
      interval: 30s  # Scrape interval
      scheme: http  # Use https if your metrics endpoint is secured